# Conclusion

In this project, our purpose is to study gender inequality by projecting the education aspect. Therefore, we investigate how gender is associated with educational inequality and what is the common characteristics of countries with poor educational performance in terms of national finances or development.  After performing exploratory research, we obtain more insights. Gender inequality still exists since females may remain under-prioritized in fundamental education, especially in countries with severe under-education and a lack of educational resources. The lower the national overall education degree, the greater the difference in education rates between males and females, and the more likely gender inequality persists. When considering development as an additional factor, it is discovered that more of these countries are found to be the least or less developed. In addition to these sound findings, which are identified as our hypothesis, an inspiring breakthrough is found: females are better represented in the data on higher education, implying that gender inequality has been improved in most countries with decent development.

We also find some limitations of this project. For instance, the limitation of the dataset of the 10-year time range makes the data less reliable for comparison. Moreover, our major limitation is that we make some assumptions. First, we only use education as a projection to assert the existence of gender inequality. Secondly, if the difference between male and female rates is high, we conclude this is a case of gender inequality. However, in reality, there might exist other reasons causing this situation. Finally, due to the large proportion of missing data points for some countries, we assume that the rates for these countries are like the other countries level of development. This assumption is mainly used in more developed countries where data are severely lacking.

For future directions, we can also focus on the least developed countries and some indicators that caused education inequality in gender, such as education policy, religion, or family income. There is the question if the education policy and religion can facilitate the education bias in gender. What kind of income status in a family will cause education bias in our society? In addition, we can figure out the outcomes that gender bias in education brings to the community or the education system. We can determine if gender inequality in education relates to gender-based violence, child marriage, and representation for women and girls at the policy level. Is the increase in gender-based violence in some countries coordinated with the higher gender inequality in education? There are more and more questions and topics we can think about based on the results we found in previous chapters.

The lessons we learned from this project: At the beginning of the project, we misunderstood the data source files and wasted time cleaning different sources. After meeting each other and checking the dataset, we found these issues, and we quickly went over the dataset and cleaned them together. So, communication and fixed update meeting are important. After realizing our mistakes, we scheduled the meeting for each chapter and updated the changes every day we did before. The next one is making use of the git branches. First, it is easy to get the merged issues because both of us push when we finish each task. Now, we have started using branches, and updating the context in git is more convenient. 

