# Data 

## Sources

Our proposed dataset was collected from multiple data sources over the past 10+ years.

1. Multiple Indicator Cluster Surveys (MICS) database: It contains information about children and women from over 200 countries round the world, such as children poverty, HIV/AIDS. All data are primary and gathered from surveys organized by UNICEF. 


2. DHS:

DHS(Demographic and Health Surveys) is a nationally representative survey that collects a wealth of information on various topics in a specific country. The data is processed and presented in the final survey report containing several tables that provide information on specific indicators in a country. The DHS Program supports a range of data collection options that can be tailored to fit host countries’ particular monitoring and evaluation needs.

The DHS Program’s basic approach is to collect comparable data across countries. To achieve this, standard model questionnaires have been developed, along with a written description of why certain questions or sections have been included. They have the model questionnaires in each country. 

Surveys with large sample sizes (usually between 5,000 and 30,000 households). In all households, women aged 15-49 are eligible to participate; in many surveys, men aged 15-54(59) from a sub-sample are also eligible to participate. There are three core questionnaires in DHS surveys: A Household Questionnaire, a Women’s Questionnaire, and a Men's questionnaire.

There are over 100 indicators regarding gender and education from our data sources. After screening, the eleven indicators which we chose to use in this project mainly come from six aspects: 

* **Completion rate** presents the percentage of cohort of children or young people three to five years older than the intended age for the last grade of each level of education (primary, lower secondary, or upper secondary) who have completed that level of education. A low completion rate indicates low or delayed entry into a given level of education, high drop-out, high repetition, late completion, or a combination of these factors. The dataset has 3 sheets, each for one level of education.


* **Out-of-school children rate** illustrates the proportion of children who fall within the prescribed age range for a particular educational level but do not attend primary, lower secondary, or higher secondary school.  The higher the out-of-school rate, the more emphasis must be placed on expanding access to education. Three sheets, one for each degree of schooling, make up the dataset.

* **Literacy rate** displays percentage of population (youth and adult) that can both read and write a short, simple statement about their everyday life. A lower rate means more of the population is illiterate. The dataset is separated into 2 sheets, each of which represents an age group. 

* **Higher education attendance** Percentage of people aged 18-22 years attending higher education.

* **Tertiary completion rate** Percentage of people aged 25–29/30–34, who have completed at least two/four years of higher education.

* **Mean years of education** Average number of years of schooling attained for the age group 20–24 years.


Several problems are discovered:

1. The time period of data collection ranges from 2010 to 2021. Most recent data is used for countries with multiple years of data. Therefore, data of some countries may be collected in 2010 while some may be collected in 2021. It raises the risk of comparison inequality. Developments over the past 10 years have likely increased access to education.

2. Since all data are collected from household surveys, the reliability of this kind of house-to-house survey is questionable. This is also the common problem of primary data source. 

3. There are many missing values in our proposed dataset. Our missing value analysis implies there are more missing values for more developed countries. Reasons and details are discussed in Section 3.3. Besides, as the dataset is assembled from multiple data sources, the incidence of missing values increases. Most countries lack at least one indicator.


## Cleaning / transformation

Since we collected 4 datasets, cleaning and transformation are performed separately. 
In datasets of completion rate, literacy rate and out-of school rate, worksheets are separated using *read_excel* from *readxl* package. Columns orther than country name, development level and indicators are all removed, leaving us a 202 $*$ 4 dataset. Regional development level is categorized into 4 levels, listed sequentially: not classified, least developed, less developed, and more developed. After transforming with *pivot_longer* (i.e, creating a categorical column for gender), each dataset is now with 404 rows and 4 columns. 


In addition, the other three indicators are all in one dataset. This dataset contains records from multiple years. Maximum values for each country are chosen instead of most recent values, since it is discovered that some countries have most recent values of 0 but valid numbers for other records. There are over 300 countries/regions in this dataset. Therefore, after combining all data frames together by country names, a data frame with 450 rows and 14 columns are obtained. Each row presents a country/region, and 11 columns records over 1900 indicator data points.


## Missing value analysis

