--- 
title: "Gender and Education"
author: "Qinqi Zhang, Yanqing Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Education is always an important aspect when assessing development, and gender equality also symbolizes development. In the past, most people had no opportunities to be educated because of financial or social status reasons. Not to mention, women had limited access to education due to gender inequality, leading to high probabilities of child marriage and teenage pregnancy[[1](https://www.worldvision.ca/stories/education/why-is-education-important#Why-is-education-important)]. 

Currently, things have been improving. As female master's students, with gratitude and celebration of modern development, the existence of gender inequality in education in recent years is proposed to be explored in this research. Multiple indicators would be used for investigation, such as youth literacy rate, out-of-school rate, etc.

In addition to considering gender, geographical factors are also taken into account. In those highly developed countries, generally, girls have the same opportunities to study as boys, and everyone has equal rights to receive an education. However, in some countries, people lack education resources, and boys might be prior to these resources. Therefore, the question of whether countries with high rates of educational underachievement are more likely to situate in gender inequality was also raised. Countries would be categorized according to their development degree and income level.

In summary, in this project, we wanted to investigate the relationship between gender and education by answering the following three questions: 1) Does gender inequality still exist? 2) If countries have lower educational attainment, is their data also highly unbalanced regarding gender disparities? 3) Do countries with gender inequality in education have similar characteristics in terms of development?

