# Interactive component

<script src="https://d3js.org/d3.v4.js"></script>
<!-- Load color palettes -->
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>

<!-- Add 2 buttons -->

<button onclick="update('prop_male')">Male</button>
<button onclick="update('prop_female')">Female</button>


<!-- Create a div where the graph will take place -->
<div id="my_dataviz"></div>

<script>

// set the dimensions and margins of the graph
const margin = {top: 80, right: 25, bottom: 30, left: 40},
  width = 450 - margin.left - margin.right,
  height = 450 - margin.top - margin.bottom;

// append the svg object to the body of the page
const svg = d3.select("#my_dataviz")
.append("svg")
  .attr("width", width + margin.left + margin.right)
  .attr("height", height + margin.top + margin.bottom)
.append("g")
  .attr("transform",
        "translate(" + margin.left + "," + margin.top + ")");

const x = d3.scaleBand()
    .range([ 0, width ])
    .padding(0.05);


const y = d3.scaleBand()
    .range([ height, 0 ])
    .padding(0.05);
  
const myColor = d3.scaleSequential()
    .interpolator(d3.interpolatePuRd)
    .domain([1,100])


 // Build X scales and axis:
  x.domain(["Least Developed","Less Developed","More Developed","Not Classified"])
  svg.append("g")
    .style("font-size", 12)
    .attr("transform", `translate(0, ${height})`)
    .call(d3.axisBottom(x).tickSize(0))
    .select(".domain").remove()
    
  // Build Y scales and axis:
  y.domain(["below 10","10 to 20","20 to 30","30 to 40","40 to 50","50 to 60","60 to 70","over 70"])

  svg.append("g")
    .style("font-size", 12)
    .call(d3.axisLeft(y).tickSize(0))
    .select(".domain").remove()
    
  const tooltip = d3.select("#my_dataviz")
    .append("div")
    .style("opacity", 0)
    .attr("class", "tooltip")
    .style("background-color", "white")
    .style("border", "solid")
    .style("border-width", "2px")
    .style("border-radius", "5px")
    .style("padding", "4px")
    
function update(selectedvar) {
//Read the data
d3.csv("https://raw.githubusercontent.com/FinalProjectGroup34/GenderEducation/main/male_female.csv", function(data) {

  // Labels of row and columns -> unique identifier of the column called 'group' and 'constiable'
  const myGroups = d3.map(data, function(d){return d.Development_Regions;}).keys()
  const myvars = d3.map(data, function(d){return d.level;}).keys()

  
  const mouseover = function(d) {
    tooltip
      .style("opacity", 1)
    d3.select(this)
      .style("stroke", "black")
      .style("opacity", 1)
  }
  

  const mousemove = function(d) {
    tooltip
      .html(d[selectedvar]+'% of countries with tertiary completion rate in range: '+d.level+' are '+d.Development_Regions)
      .style("left", event=>d3.pointer(event)[0])
      .style("top", event=>d3.pointer(event)[1])
  }
  
  const mouseleave = function(d) {
    tooltip
      .style("opacity", 0)
    d3.select(this)
      .style("stroke", "none")
      .style("opacity", 0.8)
  }
  svg.selectAll()
    .data(data, function(d) {return d.Development_Regions+':'+d.level;})
    .enter()
    .append("rect")
      .attr("x", function(d) { return x(d.Development_Regions) })
      .attr("y", function(d) { return y(d.level) })
      .attr("rx", 4)
      .attr("ry", 4)
      .attr("width", x.bandwidth() )
      .attr("height", y.bandwidth() )
      .style("fill", function(d) { return myColor(d[selectedvar])} )
      .style("stroke-width", 1)
      .style("stroke", "none")
    .on("mouseover", mouseover)
    .on("mousemove", mousemove)
    .on("mouseleave", mouseleave)

})
}

// Initialize plot
update('prop_male')

// Add title to graph
svg.append("text")
        .attr("x", 0)
        .attr("y", -50)
        .attr("text-anchor", "left")
        .style("font-size", "22px")
        .text("A d3.js heatmap");

// Add subtitle to graph
svg.append("text")
        .attr("x", 0)
        .attr("y", -20)
        .attr("text-anchor", "left")
        .style("font-size", "14px")
        .style("fill", "grey")
        .style("max-width", 400)
        .text("A short description of the take-away message of this chart.");

</script>